/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.akkapeddi.sample;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Side {
  BUY, SELL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Side\",\"namespace\":\"com.akkapeddi.sample\",\"symbols\":[\"BUY\",\"SELL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
